#!/bin/bash

addr="$1"
port="$2"

if [[ "$addr" == "" ]];then
	echo "Please enter the adress"
	exit 0
fi

if [[ "$port" == "" ]];then
	echo "Please enter the port"
	exit 0
fi

adb pair 192.168.1."${addr}":"${port}"